services:
  backend:
    build: ./server
    container_name: pingly-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build: 
      context: ./client
      args:
        # This passes the secret from your .env into the Docker build process
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    container_name: pingly-frontend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - backend